# -*- coding: utf-8 -*-
"""program1&2ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vfaZIvy9_2lJn5shBt70q-kIqToxJ9eT

Basic array creation
"""

import numpy as np
array_from_list=np.array([1,2,3,4,5])
print("Array from list:",array_from_list)

array_with_range=np.arange(10)
print("Array with range:",array_with_range)

zeros_array=np.zeros((3,3))
print("Array of zeros:\n",zeros_array)

ones_array=np.ones((2,5))
print("Array of ones:\n",ones_array)

"""Array Operations"""

import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])

add_result=np.add(a,b)
print("Addition:",add_result)

sub_result=np.subtract(a,b)
print("Subtreaction:",sub_result)

mul_result=np.multiply(a,b)
print("Multiplication:",mul_result)

div_result=np.divide(a,b)
print("Division:",div_result)

