# -*- coding: utf-8 -*-
"""program4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jAClfex5fHNEw9Q9X0vYBdWIkBqAR3QE

Indexing and slicing
"""

import numpy as np

#creating a 2D array
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D Array \n", array_2d)

#Accessing element at(1,2)
element=array_2d[1,2]
print("Element at (1,2):",element)

#slicing a subarray (rows 1 to 2, columns 0 to 1)
subarray=array_2d[1:3,0:2]
print("Sliced subarray:\n",subarray)

#Accessing a column (all rows, column 1)
column=array_2d[:,1]
print("Column 1:",column)