# -*- coding: utf-8 -*-
"""program5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zqTaPfXFBqEc7BH5rO1wm8gMILxrV4O3

Statistical Operation
"""

import numpy as np
array=np.array([1,2,3,4,5,6,7,8,9,10])

mean=np.mean(array)
print("Mean:",mean)
median=np.median(array)
print("Median:",median)
std_dev=np.std(array)
print("standard deviation:",std_dev)
min_val=np.min(array)
max_val=np.max(array)
print("Minimum value:",min_val)
print("Maximum value:",max_val)